name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *' # हर 5 मिनट में बैकग्राउंड में चेक करेगा
  workflow_dispatch: # मैनुअली तुरंत रन करने के लिए

# यहाँ गिटहब को कोड अपडेट करने की अनुमति (Permissions) दी जा रही है
permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync with Upstream using GH CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo sync Premium-png/jio-tv-auto-update-playlist -b main
