name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *' # हर 5 मिनट में ऑटोमैटिकली सिंक करेगा
  workflow_dispatch: # मैनुअली रन करने का विकल्प

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: SlamDevs/JioTV_Live
          persist-credentials: false

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: SlamDevs/JioTV_Live
